<a href="https://colab.research.google.com/github/Pranayshukla0610/ML-projects-portfolio/blob/main/Notebook_7_returns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import random
import pandas as pd
import numpy as np

from datetime import timedelta

In [36]:
random.seed(42)
np.random.seed(42)

In [37]:
order_details_df = pd.read_csv('/content/order_details (2).csv')

In [38]:
orders_df = pd.read_csv('/content/orders (2).csv')

In [39]:
print("Order Details :", order_details_df.shape)

print("Orders :", orders_df.shape)

Order Details : (300772, 8)
Orders : (100000, 14)

In [40]:
return_base = order_details_df.merge(
    orders_df[['order_id','order_date']],
    on = 'order_id',
    how = 'left'
)

In [41]:
return_base.head()

,order_detail_id,order_id,product_id,quantity,unit_price,discount_percent,line_sales,line_profit,order_date
0,OD00000001,O0000001,P00013,1,4959.77,30,3471.84,-592.38,2026-12-02
1,OD00000002,O0000002,P00126,3,10860.17,10,29322.46,5584.78,2024-03-04
2,OD00000003,O0000002,P00115,1,9392.68,0,9392.68,979.00,2024-03-04
3,OD00000004,O0000002,P00072,1,893.87,20,715.10,-4.63,2024-03-04
4,OD00000005,O0000003,P00347,2,201.40,15,342.38,17.20,2024-10-21

In [42]:
RETURN_RATE = 0.10

In [43]:
number_of_returns = int(
    len(return_base)
    * RETURN_RATE
)

print(number_of_returns)

30077

In [44]:
returned_orders = return_base.sample(
    n = number_of_returns,
    random_state = 42
).copy()

In [45]:
returned_orders.reset_index(

    drop=True,

    inplace=True

)

In [46]:
returns_base = order_details_df.merge(

    orders_df[["order_id", "order_date"]],

    on="order_id",

    how="left"

)

In [47]:
return_reasons = [

    "Damaged Product",

    "Wrong Item Delivered",

    "Customer Changed Mind",

    "Size Issue",

    "Quality Issue",

    "Late Delivery",

    "Defective Product",

    "Missing Parts",

    "Duplicate Order",

    "Other"

]

In [48]:
reason_probability = [

    0.18,

    0.10,

    0.20,

    0.10,

    0.12,

    0.08,

    0.12,

    0.05,

    0.03,

    0.02

]

In [49]:
return_status_options = [

    "Approved",

    "Rejected",

    "Pending"

]

In [50]:
return_status_probability = [

    0.80,

    0.10,

    0.10

]

In [51]:
inspection_status_options = [

    "Passed",

    "Failed",

    "Pending"
]

In [52]:
inspection_probability = [

    0.75,

    0.10,

    0.15

]

In [53]:
refund_methods = [

    "UPI",

    "Credit Card",

    "Debit Card",

    "Wallet",

    "Bank Transfer",

    "Store Credit"

]

In [54]:
return_id_list = []

order_detail_id_list = []

return_date_list = []

return_reason_list = []

refund_amount_list = []

return_status_list = []

inspection_status_list = []

restocking_fee_list = []

refund_method_list = []

In [55]:
return_counter = 1

In [56]:
print("=" * 65)

print("RETURNS DATASET CONFIGURATION")

print("=" * 65)

print("Order Detail Records :", len(order_details_df))

print("Return Rate :", RETURN_RATE * 100, "%")

print("Expected Returns :", number_of_returns)

print("=" * 65)

=================================================================
RETURNS DATASET CONFIGURATION
=================================================================
Order Detail Records : 300772
Return Rate : 10.0 %
Expected Returns : 30077
=================================================================

In [57]:
for _, row in returned_orders.iterrows():

    # Return ID
    return_id = f"RET{return_counter:06d}"
    return_counter += 1

    # Order Detail ID
    order_detail_id = row["order_detail_id"]

    # Order Date
    order_date = pd.to_datetime(row["order_date"])

    # Return Date (1–30 days after purchase)
    return_date = order_date + timedelta(
        days=random.randint(1, 30)
    )

    # Return Reason
    return_reason = np.random.choice(
        return_reasons,
        p=reason_probability
    )

    # Return Status
    return_status = np.random.choice(
        return_status_options,
        p=return_status_probability
    )

    # Inspection Status
    inspection_status = np.random.choice(
        inspection_status_options,
        p=inspection_probability
    )

    # Refund Method
    refund_method = random.choice(
        refund_methods
    )

    # Line Sales
    line_sales = row["line_sales"]

    # Restocking Fee
    if return_reason in [
        "Customer Changed Mind",
        "Duplicate Order"
    ]:

        restocking_fee = round(
            line_sales * random.uniform(0.05, 0.10),
            2
        )

    else:

        restocking_fee = 0

    # Refund Amount
    if return_status == "Approved":

        refund_amount = round(
            line_sales - restocking_fee,
            2
        )

    else:

        refund_amount = 0

    # Store Data

    return_id_list.append(return_id)

    order_detail_id_list.append(order_detail_id)

    return_date_list.append(return_date)

    return_reason_list.append(return_reason)

    refund_amount_list.append(refund_amount)

    return_status_list.append(return_status)

    inspection_status_list.append(inspection_status)

    restocking_fee_list.append(restocking_fee)

    refund_method_list.append(refund_method)

In [58]:
returns_df = pd.DataFrame({

    "return_id": return_id_list,

    "order_detail_id": order_detail_id_list,

    "return_date": return_date_list,

    "return_reason": return_reason_list,

    "refund_amount": refund_amount_list,

    "return_status": return_status_list,

    "inspection_status": inspection_status_list,

    "restocking_fee": restocking_fee_list,

    "refund_method": refund_method_list

})

In [59]:
returns_df["refund_amount"].describe()

count     30077.000000
mean      21363.044810
std       48562.119389
min           0.000000
25%         819.560000
50%        4867.920000
75%       19321.990000
max      692605.250000
Name: refund_amount, dtype: float64

In [60]:
returns_df.sort_values(
    by = "refund_amount",
    ascending=False
).head(10)

,return_id,order_detail_id,return_date,return_reason,refund_amount,return_status,inspection_status,restocking_fee,refund_method
2428,RET002429,OD00289042,2025-08-19,Wrong Item Delivered,692605.25,Approved,Passed,0.00,Wallet
428,RET000429,OD00186809,2023-07-02,Customer Changed Mind,633038.61,Approved,Passed,59566.64,Credit Card
19209,RET019210,OD00039190,2026-08-03,Other,629283.25,Approved,Passed,0.00,Debit Card
26109,RET026110,OD00026571,2026-11-26,Quality Issue,629283.25,Approved,Passed,0.00,UPI
23823,RET023824,OD00023807,2025-09-18,Wrong Item Delivered,629283.25,Approved,Pending,0.00,Debit Card
24751,RET024752,OD00038968,2023-06-11,Late Delivery,616034.52,Approved,Failed,0.00,Wallet
15401,RET015402,OD00169240,2026-11-14,Missing Parts,616034.52,Approved,Passed,0.00,UPI
11218,RET011219,OD00282686,2024-12-31,Quality Issue,608524.80,Approved,Passed,0.00,Debit Card
12307,RET012308,OD00278611,2023-01-07,Late Delivery,608524.80,Approved,Passed,0.00,UPI
26219,RET026220,OD00076473,2023-10-13,Wrong Item Delivered,603931.64,Approved,Passed,0.00,Credit Card

In [61]:
returns_df.sort_values(
    by="restocking_fee",
    ascending=False
).head(10)

,return_id,order_detail_id,return_date,return_reason,refund_amount,return_status,inspection_status,restocking_fee,refund_method
428,RET000429,OD00186809,2023-07-02,Customer Changed Mind,633038.61,Approved,Passed,59566.64,Credit Card
25049,RET025050,OD00157765,2025-06-01,Duplicate Order,581812.35,Approved,Passed,47470.90,Debit Card
20453,RET020454,OD00277075,2026-05-22,Customer Changed Mind,463387.29,Approved,Passed,46202.83,Store Credit
7939,RET007940,OD00195947,2025-01-14,Customer Changed Mind,580852.14,Approved,Failed,42492.58,UPI
24319,RET024320,OD00065520,2026-03-02,Customer Changed Mind,465038.07,Approved,Passed,41816.63,UPI
16672,RET016673,OD00220108,2023-05-20,Customer Changed Mind,510514.25,Approved,Passed,40293.09,Store Credit
7992,RET007993,OD00194663,2024-09-27,Customer Changed Mind,0.00,Pending,Passed,39827.87,Credit Card
12326,RET012327,OD00203445,2026-01-13,Customer Changed Mind,0.00,Pending,Passed,38785.88,UPI
13377,RET013378,OD00046443,2025-02-13,Customer Changed Mind,0.00,Pending,Passed,38534.25,Wallet
8550,RET008551,OD00288870,2024-10-23,Customer Changed Mind,509691.91,Approved,Passed,37813.19,Wallet

In [62]:
returns_df[
    returns_df["return_status"] == "Approved"
].sample(10)

,return_id,order_detail_id,return_date,return_reason,refund_amount,return_status,inspection_status,restocking_fee,refund_method
11357,RET011358,OD00068925,2023-09-30,Size Issue,1693.64,Approved,Passed,0.00,Debit Card
8255,RET008256,OD00147063,2026-01-29,Defective Product,2743.58,Approved,Passed,0.00,Bank Transfer
16780,RET016781,OD00007418,2024-07-10,Missing Parts,51870.00,Approved,Passed,0.00,Credit Card
28031,RET028032,OD00235935,2026-11-20,Size Issue,9365.27,Approved,Passed,0.00,Store Credit
29813,RET029814,OD00224232,2026-09-09,Defective Product,1643.23,Approved,Passed,0.00,Credit Card
17537,RET017538,OD00195428,2024-08-24,Damaged Product,70777.77,Approved,Pending,0.00,Store Credit
21785,RET021786,OD00217354,2023-06-24,Quality Issue,23082.15,Approved,Passed,0.00,Wallet
22431,RET022432,OD00092488,2025-03-12,Customer Changed Mind,62548.47,Approved,Passed,6611.53,Debit Card
17869,RET017870,OD00047644,2023-11-27,Defective Product,3186.35,Approved,Passed,0.00,Credit Card
27013,RET027014,OD00032090,2025-02-23,Wrong Item Delivered,94746.88,Approved,Passed,0.00,Debit Card

In [63]:
returns_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30077 entries, 0 to 30076
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   return_id          30077 non-null  object
 1   order_detail_id    30077 non-null  object
 2   return_date        30077 non-null  datetime64[ns]
 3   return_reason      30077 non-null  object
 4   refund_amount      30077 non-null  float64
 5   return_status      30077 non-null  object
 6   inspection_status  30077 non-null  object
 7   restocking_fee     30077 non-null  float64
 8   refund_method      30077 non-null  object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 2.1+ MB

In [64]:
returns_df.isnull().sum()

return_id            0
order_detail_id      0
return_date          0
return_reason        0
refund_amount        0
return_status        0
inspection_status    0
restocking_fee       0
refund_method        0
dtype: int64

In [65]:
returns_df['return_id'].duplicated().sum()

np.int64(0)

In [66]:
invalid_order_details = returns_df[
    ~returns_df['order_detail_id'].isin(
        order_details_df['order_detail_id']

    )
]

In [67]:
duplicate_returns = returns_df.duplicated(
    subset=["order_detail_id"]
).sum()

print("Duplicate Returned Items :", duplicate_returns)

Duplicate Returned Items : 0

In [68]:
validation_df = returns_df.merge(

    returns_base[
        ["order_detail_id", "order_date"]
    ],

    on="order_detail_id",

    how="left"

)

validation_df["order_date"] = pd.to_datetime(
    validation_df["order_date"]
)

invalid_dates = validation_df[
    validation_df["return_date"] <
    validation_df["order_date"]
]

print("Invalid Return Dates :", len(invalid_dates))

Invalid Return Dates : 0

In [69]:
print(
    "Negative Refund Amounts :",
    (returns_df["refund_amount"] < 0).sum()
)

Negative Refund Amounts : 0

In [70]:
print(
    "Negative Restocking Fees :",
    (returns_df["restocking_fee"] < 0).sum()
)

Negative Restocking Fees : 0

In [71]:
approved_zero = returns_df[
    (returns_df["return_status"] == "Approved") &
    (returns_df["refund_amount"] == 0)
]

print("Approved Returns with Zero Refund :", len(approved_zero))

Approved Returns with Zero Refund : 0

In [72]:
rejected_refund = returns_df[
    (returns_df["return_status"] == "Rejected") &
    (returns_df["refund_amount"] > 0)
]

print("Rejected Returns with Refund :", len(rejected_refund))

Rejected Returns with Refund : 0

In [73]:
pending_refund = returns_df[
    (returns_df["return_status"] == "Pending") &
    (returns_df["refund_amount"] > 0)
]

print("Pending Returns with Refund :", len(pending_refund))

Pending Returns with Refund : 0

In [74]:
returns_df.sort_values(
    by="refund_amount",
    ascending=False
).head(10)

,return_id,order_detail_id,return_date,return_reason,refund_amount,return_status,inspection_status,restocking_fee,refund_method
2428,RET002429,OD00289042,2025-08-19,Wrong Item Delivered,692605.25,Approved,Passed,0.00,Wallet
428,RET000429,OD00186809,2023-07-02,Customer Changed Mind,633038.61,Approved,Passed,59566.64,Credit Card
19209,RET019210,OD00039190,2026-08-03,Other,629283.25,Approved,Passed,0.00,Debit Card
26109,RET026110,OD00026571,2026-11-26,Quality Issue,629283.25,Approved,Passed,0.00,UPI
23823,RET023824,OD00023807,2025-09-18,Wrong Item Delivered,629283.25,Approved,Pending,0.00,Debit Card
24751,RET024752,OD00038968,2023-06-11,Late Delivery,616034.52,Approved,Failed,0.00,Wallet
15401,RET015402,OD00169240,2026-11-14,Missing Parts,616034.52,Approved,Passed,0.00,UPI
11218,RET011219,OD00282686,2024-12-31,Quality Issue,608524.80,Approved,Passed,0.00,Debit Card
12307,RET012308,OD00278611,2023-01-07,Late Delivery,608524.80,Approved,Passed,0.00,UPI
26219,RET026220,OD00076473,2023-10-13,Wrong Item Delivered,603931.64,Approved,Passed,0.00,Credit Card

In [75]:
returns_df.sort_values(
    by="restocking_fee",
    ascending=False
).head(10)

,return_id,order_detail_id,return_date,return_reason,refund_amount,return_status,inspection_status,restocking_fee,refund_method
428,RET000429,OD00186809,2023-07-02,Customer Changed Mind,633038.61,Approved,Passed,59566.64,Credit Card
25049,RET025050,OD00157765,2025-06-01,Duplicate Order,581812.35,Approved,Passed,47470.90,Debit Card
20453,RET020454,OD00277075,2026-05-22,Customer Changed Mind,463387.29,Approved,Passed,46202.83,Store Credit
7939,RET007940,OD00195947,2025-01-14,Customer Changed Mind,580852.14,Approved,Failed,42492.58,UPI
24319,RET024320,OD00065520,2026-03-02,Customer Changed Mind,465038.07,Approved,Passed,41816.63,UPI
16672,RET016673,OD00220108,2023-05-20,Customer Changed Mind,510514.25,Approved,Passed,40293.09,Store Credit
7992,RET007993,OD00194663,2024-09-27,Customer Changed Mind,0.00,Pending,Passed,39827.87,Credit Card
12326,RET012327,OD00203445,2026-01-13,Customer Changed Mind,0.00,Pending,Passed,38785.88,UPI
13377,RET013378,OD00046443,2025-02-13,Customer Changed Mind,0.00,Pending,Passed,38534.25,Wallet
8550,RET008551,OD00288870,2024-10-23,Customer Changed Mind,509691.91,Approved,Passed,37813.19,Wallet

In [76]:
import os

os.makedirs(
    "Data/Generated",
    exist_ok=True
)

In [77]:
returns_df.to_csv(
    "Data/Generated/returns.csv",
    index=False
)

In [78]:
from google.colab import files

files.download(
    "Data/Generated/returns.csv"
)