<a href="https://colab.research.google.com/github/Pranayshukla0610/ML-projects-portfolio/blob/main/Python_with_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [4]:
import sqlite3

conn = sqlite3.connect("/content/superstore.db")

cursor = conn.cursor()

In [5]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS sales(

row_id INTEGER PRIMARY KEY,

order_id TEXT,
order_date TEXT,
ship_date TEXT,
ship_mode TEXT,

customer_id TEXT,
customer_name TEXT,
segment TEXT,

country TEXT,
city TEXT,
state TEXT,
postal_code TEXT,
region TEXT,

product_id TEXT,

category TEXT,
sub_category TEXT,
product_name TEXT,

sales REAL,
quantity INTEGER,
discount REAL,
profit REAL

)
""")

conn.commit()
conn.close()

print("Database Created")

Database Created

In [10]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [11]:
import sqlite3

conn = sqlite3.connect('/content/superstore.db')

cursor = conn.cursor()

cursor.execute("PRAGMA table_info(sales)")

for row in cursor.fetchall():
    print(row)

(0, 'row_id', 'INTEGER', 0, None, 1)
(1, 'order_id', 'TEXT', 0, None, 0)
(2, 'order_date', 'TEXT', 0, None, 0)
(3, 'ship_date', 'TEXT', 0, None, 0)
(4, 'ship_mode', 'TEXT', 0, None, 0)
(5, 'customer_id', 'TEXT', 0, None, 0)
(6, 'customer_name', 'TEXT', 0, None, 0)
(7, 'segment', 'TEXT', 0, None, 0)
(8, 'country', 'TEXT', 0, None, 0)
(9, 'city', 'TEXT', 0, None, 0)
(10, 'state', 'TEXT', 0, None, 0)
(11, 'postal_code', 'TEXT', 0, None, 0)
(12, 'region', 'TEXT', 0, None, 0)
(13, 'product_id', 'TEXT', 0, None, 0)
(14, 'category', 'TEXT', 0, None, 0)
(15, 'sub_category', 'TEXT', 0, None, 0)
(16, 'product_name', 'TEXT', 0, None, 0)
(17, 'sales', 'REAL', 0, None, 0)
(18, 'quantity', 'INTEGER', 0, None, 0)
(19, 'discount', 'REAL', 0, None, 0)
(20, 'profit', 'REAL', 0, None, 0)

In [12]:
df.columns = [
    'row_id',
    'order_id',
    'order_date',
    'ship_date',
    'ship_mode',
    'customer_id',
    'customer_name',
    'segment',
    'country',
    'city',
    'state',
    'postal_code',
    'region',
    'product_id',
    'category',
    'sub_category',
    'product_name',
    'sales',
    'quantity',
    'discount',
    'profit'
]

In [17]:
df.columns = (
    df.columns
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [18]:
df.to_sql(
    'sales',
    conn,
    if_exists='append',
    index=False
)

9994

In [19]:
conn = sqlite3.connect('/content/superstore.db')
curson = conn.cursor()
cursor.execute(
    """SELECT COUNT(*)
    FROM Sales"""
)
print(cursor.fetchone())
conn.close()

(9994,)

In [20]:
cursor.execute(
    """PRAGMA table_info(sales)"""
)

for row in cursor.fetchall():
  print(row)

(0, 'row_id', 'INTEGER', 0, None, 1)
(1, 'order_id', 'TEXT', 0, None, 0)
(2, 'order_date', 'TEXT', 0, None, 0)
(3, 'ship_date', 'TEXT', 0, None, 0)
(4, 'ship_mode', 'TEXT', 0, None, 0)
(5, 'customer_id', 'TEXT', 0, None, 0)
(6, 'customer_name', 'TEXT', 0, None, 0)
(7, 'segment', 'TEXT', 0, None, 0)
(8, 'country', 'TEXT', 0, None, 0)
(9, 'city', 'TEXT', 0, None, 0)
(10, 'state', 'TEXT', 0, None, 0)
(11, 'postal_code', 'TEXT', 0, None, 0)
(12, 'region', 'TEXT', 0, None, 0)
(13, 'product_id', 'TEXT', 0, None, 0)
(14, 'category', 'TEXT', 0, None, 0)
(15, 'sub_category', 'TEXT', 0, None, 0)
(16, 'product_name', 'TEXT', 0, None, 0)
(17, 'sales', 'REAL', 0, None, 0)
(18, 'quantity', 'INTEGER', 0, None, 0)
(19, 'discount', 'REAL', 0, None, 0)
(20, 'profit', 'REAL', 0, None, 0)

In [21]:
import sqlite3

conn = sqlite3.connect("/content/superstore.db")

cursor = conn.cursor()

cursor.execute("""

DELETE FROM sales
WHERE customer_name IS NULL

""")

cursor.execute("""

UPDATE sales
SET city = TRIM(city)

""")

cursor.execute("""

UPDATE sales
SET state = UPPER(state)

""")

conn.commit()

conn.close()

print("Cleaning Completed")

Cleaning Completed

In [22]:
#TOTAL REVENUE
import sqlite3
conn = sqlite3.connect('/content/superstore.db')
query = """
SELECT ROUND(SUM(sales),2)
FROM sales"""

result = conn.execute(query)
print(result.fetchall())
conn.close()

[(2297200.86,)]

In [25]:
import sqlite3

conn = sqlite3.connect('/content/superstore.db')
cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

print(cursor.fetchall())

conn.close()

[('sales',)]

In [28]:
import sqlite3

conn = sqlite3.connect('/content/superstore.db')
cursor = conn.cursor()

# Customers
cursor.execute("""
CREATE TABLE IF NOT EXISTS customers AS
SELECT DISTINCT
customer_id,
customer_name,
segment,
city,
state,
country
FROM sales
""")

# Products
cursor.execute("""
CREATE TABLE IF NOT EXISTS products AS
SELECT DISTINCT
product_id,
product_name,
category,
sub_category
FROM sales
""")

# Orders
cursor.execute("""
CREATE TABLE IF NOT EXISTS orders AS
SELECT
order_id,
customer_id,
product_id,
sales,
quantity,
profit,
order_date
FROM sales
""")

conn.commit()
conn.close()

print("Tables Created Successfully")

Tables Created Successfully

In [29]:
import sqlite3

conn = sqlite3.connect('/content/superstore.db')
cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

print(cursor.fetchall())

conn.close()

[('sales',), ('customers',), ('products',), ('orders',)]

In [30]:
import sqlite3

conn = sqlite3.connect('/content/superstore.db')
cursor = conn.cursor()

query = """
SELECT
o.order_id,
c.customer_name,
p.product_name,
o.sales

FROM orders o

JOIN customers c
ON o.customer_id = c.customer_id

JOIN products p
ON o.product_id = p.product_id

LIMIT 10
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

conn.close()

('CA-2016-152156', 'Claire Gute', 'Bush Somerset Collection Bookcase', 261.96)
('CA-2016-152156', 'Claire Gute', 'Bush Somerset Collection Bookcase', 261.96)
('CA-2016-152156', 'Claire Gute', 'Bush Somerset Collection Bookcase', 261.96)
('CA-2016-152156', 'Claire Gute', 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 731.94)
('CA-2016-152156', 'Claire Gute', 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 731.94)
('CA-2016-152156', 'Claire Gute', 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 731.94)
('CA-2016-138688', 'Darrin Van Huff', 'Self-Adhesive Address Labels for Typewriters by Universal', 14.62)
('CA-2016-138688', 'Darrin Van Huff', 'Self-Adhesive Address Labels for Typewriters by Universal', 14.62)
('CA-2016-138688', 'Darrin Van Huff', 'Self-Adhesive Address Labels for Typewriters by Universal', 14.62)
('CA-2016-138688', 'Darrin Van Huff', 'Self-Adhesive Address Labels for Typewriters by Universal', 14.62)

In [32]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('/content/superstore.db')

In [33]:
query = """

SELECT

o.order_id,
c.customer_name,
p.product_name,
o.sales

FROM orders o

JOIN customers c
ON o.customer_id = c.customer_id

JOIN products p
ON o.product_id = p.product_id

LIMIT 20

"""

df = pd.read_sql_query(query, conn)

df

,order_id,customer_name,product_name,sales
0,CA-2016-152156,Claire Gute,Bush Somerset Collection Bookcase,261.9600
1,CA-2016-152156,Claire Gute,Bush Somerset Collection Bookcase,261.9600
2,CA-2016-152156,Claire Gute,Bush Somerset Collection Bookcase,261.9600
3,CA-2016-152156,Claire Gute,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
4,CA-2016-152156,Claire Gute,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
5,CA-2016-152156,Claire Gute,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
6,CA-2016-138688,Darrin Van Huff,Self-Adhesive Address Labels for Typewriters b...,14.6200
7,CA-2016-138688,Darrin Van Huff,Self-Adhesive Address Labels for Typewriters b...,14.6200
8,CA-2016-138688,Darrin Van Huff,Self-Adhesive Address Labels for Typewriters b...,14.6200
9,CA-2016-138688,Darrin Van Huff,Self-Adhesive Address Labels for Typewriters b...,14.6200
10,CA-2016-138688,Darrin Van Huff,Self-Adhesive Address Labels for Typewriters b...,14.6200
11,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
12,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
13,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
14,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
15,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
16,US-2015-108966,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775
17,US-2015-108966,Sean O'Donnell,Eldon Fold 'N Roll Cart System,22.3680
18,US-2015-108966,Sean O'Donnell,Eldon Fold 'N Roll Cart System,22.3680
19,US-2015-108966,Sean O'Donnell,Eldon Fold 'N Roll Cart System,22.3680

In [34]:
query = """

SELECT

c.customer_name,
o.order_id,
o.sales

FROM customers c

LEFT JOIN orders o

ON c.customer_id = o.customer_id

LIMIT 20

"""

pd.read_sql_query(query, conn)

      customer_name        order_id    sales
0       Claire Gute  CA-2016-152156  261.960
1       Claire Gute  CA-2016-152156  731.940
2       Claire Gute  CA-2017-164098   18.160
3       Claire Gute  US-2015-123918    5.344
4       Claire Gute  US-2015-123918  131.376
5   Darrin Van Huff  CA-2016-106656    4.080
6   Darrin Van Huff  CA-2016-106656   18.900
7   Darrin Van Huff  CA-2016-138688   14.620
8   Darrin Van Huff  CA-2017-125745   19.520
9   Darrin Van Huff  CA-2017-139773  188.552
10  Darrin Van Huff  CA-2017-168389   13.584
11  Darrin Van Huff  CA-2017-168389   64.784
12  Darrin Van Huff  CA-2017-168389   73.568
13  Darrin Van Huff  CA-2017-168389  721.875
14   Sean O'Donnell  CA-2015-161718   28.440
15   Sean O'Donnell  CA-2015-161718   39.960
16   Sean O'Donnell  CA-2015-161718  361.764
17   Sean O'Donnell  CA-2015-161718  364.410
18   Sean O'Donnell  CA-2017-101700   11.664
19   Sean O'Donnell  CA-2017-101700   18.688

In [36]:
#Aggregations

query = """

SELECT

customer_id,
SUM(sales) total_sales

FROM orders

GROUP BY customer_id

ORDER BY total_sales DESC

LIMIT 10

"""

pd.read_sql_query(query, conn)

  customer_id  total_sales
0    SM-20320    25043.050
1    TC-20980    19052.218
2    RB-19360    15117.339
3    TA-21385    14595.620
4    AB-10105    14473.571
5    KL-16645    14175.229
6    SC-20095    14142.334
7    HL-15040    12873.298
8    SE-20110    12209.438
9    CC-12370    12129.072

In [37]:
#CTE
query = """

WITH customer_sales AS

(

SELECT

customer_id,
SUM(sales) total_sales

FROM orders

GROUP BY customer_id

)

SELECT *

FROM customer_sales

WHERE total_sales > 10000

ORDER BY total_sales DESC

"""

pd.read_sql_query(query, conn)

   customer_id  total_sales
0     SM-20320    25043.050
1     TC-20980    19052.218
2     RB-19360    15117.339
3     TA-21385    14595.620
4     AB-10105    14473.571
5     KL-16645    14175.229
6     SC-20095    14142.334
7     HL-15040    12873.298
8     SE-20110    12209.438
9     CC-12370    12129.072
10    TS-21370    11891.751
11    GT-14710    11820.120
12    BM-11140    11789.630
13    SV-20365    11470.950
14    CJ-12010    11164.974
15    CL-12565    10880.546
16    ME-17320    10663.728
17    KF-16285    10604.266
18    BS-11365    10501.653
19    EH-13765    10310.880

In [38]:
#Window Function - ROW_NUMBER

query = """

SELECT

customer_id,

SUM(sales) total_sales,

ROW_NUMBER()

OVER(

ORDER BY SUM(sales) DESC

)

AS row_num

FROM orders

GROUP BY customer_id

"""

pd.read_sql_query(query, conn)

    customer_id  total_sales  row_num
0      SM-20320    25043.050        1
1      TC-20980    19052.218        2
2      RB-19360    15117.339        3
3      TA-21385    14595.620        4
4      AB-10105    14473.571        5
..          ...          ...      ...
788    RS-19870       22.328      789
789    MG-18205       16.739      790
790    CJ-11875       16.520      791
791    LD-16855        5.304      792
792    TS-21085        4.833      793

[793 rows x 3 columns]

In [39]:
#Window Function - RANK

query = """

SELECT

customer_id,

SUM(sales) total_sales,

RANK()

OVER(

ORDER BY SUM(sales) DESC

)

AS ranking

FROM orders

GROUP BY customer_id

"""

pd.read_sql_query(query, conn)

    customer_id  total_sales  ranking
0      SM-20320    25043.050        1
1      TC-20980    19052.218        2
2      RB-19360    15117.339        3
3      TA-21385    14595.620        4
4      AB-10105    14473.571        5
..          ...          ...      ...
788    RS-19870       22.328      789
789    MG-18205       16.739      790
790    CJ-11875       16.520      791
791    LD-16855        5.304      792
792    TS-21085        4.833      793

[793 rows x 3 columns]

In [40]:
#DENSE_RANK

query = """

SELECT

customer_id,

SUM(sales) total_sales,

DENSE_RANK()

OVER(

ORDER BY SUM(sales) DESC

)

AS dense_rank

FROM orders

GROUP BY customer_id

"""

pd.read_sql_query(query, conn)

    customer_id  total_sales  dense_rank
0      SM-20320    25043.050           1
1      TC-20980    19052.218           2
2      RB-19360    15117.339           3
3      TA-21385    14595.620           4
4      AB-10105    14473.571           5
..          ...          ...         ...
788    RS-19870       22.328         789
789    MG-18205       16.739         790
790    CJ-11875       16.520         791
791    LD-16855        5.304         792
792    TS-21085        4.833         793

[793 rows x 3 columns]

In [41]:
#NTILE

query = """

SELECT

customer_id,

SUM(sales) total_sales,

NTILE(3)

OVER(

ORDER BY SUM(sales)

)

AS segment

FROM orders

GROUP BY customer_id

"""

pd.read_sql_query(query, conn)

    customer_id  total_sales  segment
0      TS-21085        4.833        1
1      LD-16855        5.304        1
2      CJ-11875       16.520        1
3      MG-18205       16.739        1
4      RS-19870       22.328        1
..          ...          ...      ...
788    AB-10105    14473.571        3
789    TA-21385    14595.620        3
790    RB-19360    15117.339        3
791    TC-20980    19052.218        3
792    SM-20320    25043.050        3

[793 rows x 3 columns]

In [42]:
#Running Total
query = """

SELECT

order_date,

SUM(sales) daily_sales,

SUM(SUM(sales))

OVER(

ORDER BY order_date

)

AS running_total

FROM orders

GROUP BY order_date

"""

pd.read_sql_query(query, conn)

     order_date  daily_sales  running_total
0      1/1/2017    1481.8280   1.481828e+03
1     1/10/2014      54.8300   1.536658e+03
2     1/10/2015    1018.1040   2.554762e+03
3     1/10/2016     174.7500   2.729512e+03
4     1/11/2014       9.9400   2.739452e+03
...         ...          ...            ...
1232   9/8/2016    4493.9836   2.286532e+06
1233   9/8/2017    2184.3270   2.288716e+06
1234   9/9/2014    4043.5880   2.292760e+06
1235   9/9/2016      84.9920   2.292845e+06
1236   9/9/2017    4356.0610   2.297201e+06

[1237 rows x 3 columns]